services:
  - type: web
    name: p2p-signaling-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node signaling-server.js
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production